// Generated by cpp11: do not edit by hand
// clang-format off


#include "cpp11/declarations.hpp"
#include <R_ext/Visibility.h>

// grepvec.cpp
SEXP grepvec_regex_(cpp11::strings needles, cpp11::strings haystck, int matchrule, bool ignorecase);
extern "C" SEXP _grepvec_grepvec_regex_(SEXP needles, SEXP haystck, SEXP matchrule, SEXP ignorecase) {
  BEGIN_CPP11
    return cpp11::as_sexp(grepvec_regex_(cpp11::as_cpp<cpp11::decay_t<cpp11::strings>>(needles), cpp11::as_cpp<cpp11::decay_t<cpp11::strings>>(haystck), cpp11::as_cpp<cpp11::decay_t<int>>(matchrule), cpp11::as_cpp<cpp11::decay_t<bool>>(ignorecase)));
  END_CPP11
}
// grepvec.cpp
SEXP grepvec_fixed_(cpp11::strings needles, cpp11::strings haystck, int matchrule, bool ignorecase);
extern "C" SEXP _grepvec_grepvec_fixed_(SEXP needles, SEXP haystck, SEXP matchrule, SEXP ignorecase) {
  BEGIN_CPP11
    return cpp11::as_sexp(grepvec_fixed_(cpp11::as_cpp<cpp11::decay_t<cpp11::strings>>(needles), cpp11::as_cpp<cpp11::decay_t<cpp11::strings>>(haystck), cpp11::as_cpp<cpp11::decay_t<int>>(matchrule), cpp11::as_cpp<cpp11::decay_t<bool>>(ignorecase)));
  END_CPP11
}

extern "C" {
static const R_CallMethodDef CallEntries[] = {
    {"_grepvec_grepvec_fixed_", (DL_FUNC) &_grepvec_grepvec_fixed_, 4},
    {"_grepvec_grepvec_regex_", (DL_FUNC) &_grepvec_grepvec_regex_, 4},
    {NULL, NULL, 0}
};
}

extern "C" attribute_visible void R_init_grepvec(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  R_forceSymbols(dll, TRUE);
}
