#include <R.h>
#include <Rinternals.h>
#include <stdlib.h> // for NULL
#include <R_ext/Rdynload.h>

/* .Call calls */
extern SEXP C_grepvec(void *, void *, void *, void *, void *, void *, void *, void *);
extern SEXP C_on_exit_grepvec(void);

static const R_CallMethodDef CallEntries[] = {
    {"C_grepvec",         (DL_FUNC) &C_grepvec,         8},
    {"C_on_exit_grepvec", (DL_FUNC) &C_on_exit_grepvec, 0},
    {NULL, NULL, 0}
};

void R_init_grepvec(DllInfo *dll)
{
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}

// file generated by:
// tools::package_native_routine_registration_skeleton(".")