#include <R.h>
#include <Rinternals.h>
#include <stdlib.h> // for NULL
#include <R_ext/Rdynload.h>


/* .Call calls */
extern SEXP grepvec_fixed(void *, void *, void *, void *);
extern SEXP grepvec_regex(void *, void *, void *, void *);

static const R_CallMethodDef CallEntries[] = {
    {"grepvec_fixed", (DL_FUNC) &grepvec_fixed, 4},
    {"grepvec_regex", (DL_FUNC) &grepvec_regex, 4},
    {NULL, NULL, 0}
};

void R_init_grepvec(DllInfo *dll)
{
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}

// note: file generated by tools::package_native_routine_registration_skeleton(".")