/* lib/tre-config.h.  Generated from tre-config.h.in by configure.  */
/* tre-config.h.in.  This file has all definitions that are needed in
   `tre.h'.  Note that this file must contain only the bare minimum
   of definitions without the TRE_ prefix to avoid conflicts between
   definitions here and definitions included from somewhere else. */

/*
   HE: the first section is identical to the "tre-config.h" in R's source code.
   It is not generated by R's configure script - i.e., these definitions are
   constant in R's source code.
*/

/* Define if you want to enable approximate matching functionality. */
#define TRE_APPROX 1

/* Define to enable multibyte character set support. */
#define TRE_MULTIBYTE 1

/* Define to a field in the regex_t struct where TRE should store a pointer to
   the internal tre_tnfa_t structure */
#define TRE_REGEX_T_FIELD value

/* Define if you want TRE to use alloca() instead of malloc() when allocating
   memory needed for regexec operations. */
/* #define TRE_USE_ALLOCA 1 */

/* Define to enable wide character (wchar_t) support. */
// #define TRE_WCHAR 1
#undef TRE_WCHAR // HE

/* TRE version string. */
#define TRE_VERSION "0.8.0"


/*
   HE: add additional definitions used in the modified TRE library that
      are defined in the R source at src/gnuwin32/fixed/h/config.h
*/

/* Define to 1 if you have the `mbrtowc' function. */
// #define HAVE_MBRTOWC 1
#undef HAVE_MBRTOWC //HE

/* Define to 1 if the system has the type `mbstate_t'. */
// #define HAVE_MBSTATE_T 1
#undef HAVE_MBSTATE_T //HE

#ifdef TRE_WCHAR
#include <wchar.h> // HE
#include <wctype.h> // HE
#endif /*TRE_WCHAR*/