# Generated by cpp11: do not edit by hand

on_exit_grepvec_ <- function() {
  .Call(`_grepvec_on_exit_grepvec_`)
}

grepvec_regex_ <- function(needles, haystck, matchrule, ignorecase) {
  .Call(`_grepvec_grepvec_regex_`, needles, haystck, matchrule, ignorecase)
}

grepvec_fixed_ <- function(needles, haystck, matchrule, ignorecase) {
  .Call(`_grepvec_grepvec_fixed_`, needles, haystck, matchrule, ignorecase)
}
