# Generated by cpp11: do not edit by hand

grepvec_regex_ <- function(needles, haystck, matchrule, ignorecase) {
  .Call(`_grepvec_grepvec_regex_`, needles, haystck, matchrule, ignorecase)
}

grepvec_fixed_ <- function(needles, haystck, matchrule, ignorecase) {
  .Call(`_grepvec_grepvec_fixed_`, needles, haystck, matchrule, ignorecase)
}
